version: "3.1"

services:
  postgres:
    image: postgres
    container_name: spaceship_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spaceship-network
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "3006:80"
    depends_on:
      - postgres
    networks:
      - spaceship-network

volumes:
  postgres_data:
    driver: local

networks:
  spaceship-network:
    driver: bridge